tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "blueutil"
brew "composer"
brew "dockutil"
brew "exa"
brew "fzf"
brew "git"
brew "gpg"
brew "grip"
brew "hub"
brew "mas"
brew "mysql@5.7", restart_service: true, link: true, conflicts_with: ["mysql"]
brew "nmap"
brew "npm"
brew "pinentry-mac"
brew "php"
brew "php-cs-fixer"
brew "prettier"
brew "private-internet-access"
brew "rbenv"
brew "rg"
brew "shellcheck"
brew "ssh-copy-id"
brew "telnet"
brew "tree"
brew "zplug"
brew "zsh"
cask "adobe-creative-cloud"
cask "1password"
cask "appcleaner"
cask "balenaetcher"
cask "battle-net"
cask "dash"
cask "discord"
cask "epic-games"
cask "fork"
cask "microsoft-office"
cask "munki"
cask "ngrok"
cask "parallels"
cask "parsec"
cask "phpstorm"
cask "postman"
cask "sequel-pro"
cask "spectacle"
cask "steam"
cask "the-unarchiver"
cask "tor-browser"
cask "vagrant"
cask "visual-studio-code"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
mas "Wipr", id: 1320666476
