tap "AdoptOpenJDK/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "composer"
brew "dockutil"
brew "elixir"
brew "exa"
brew "fzf"
brew "git"
brew "gpg"
brew "grip"
brew "hub"
brew "mailhog"
brew "mas"
brew "mysql@5.7", restart_service: true, link: true, conflicts_with: ["mysql"]
brew "neofetch"
brew "nmap"
brew "npm"
brew "pinentry-mac"
brew "php"
brew "php-cs-fixer"
brew "prettier"
brew "rbenv"
brew "rg"
brew "shellcheck"
brew "ssh-copy-id"
brew "telnet"
brew "thefuck"
brew "tree"
brew "zplug"
brew "zsh"
cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "adoptopenjdk8"
cask "appcleaner"
cask "balenaetcher"
cask "battle-net"
cask "dash"
cask "discord"
cask "epic-games"
cask "fork"
cask "google-chrome"
cask "microsoft-office"
cask "microsoft-teams"
cask "minecraft"
cask "munki"
cask "ngrok"
cask "packages"
cask "parsec"
cask "pgadmin4"
cask "phpstorm"
cask "postgres"
cask "postman"
cask "private-internet-access"
cask "pycharm"
cask "sequel-pro"
cask "spectacle"
cask "steam"
cask "teamviewer"
cask "the-unarchiver"
cask "visual-studio-code"
mas "Apple Remote Desktop", id: 409907375
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
mas "Wipr", id: 1320666476
