#!/bin/sh
# Run by github/github codespaces after starting

# Fix github GPG
if [ -d "/workspaces/github" ]; then
  git -C /workspaces/github config gpg.program /.codespaces/bin/gh-gpgsign
fi

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "root.*/bin/zsh" /etc/passwd; then
  chsh -s /bin/zsh root
fi

# Install some developer tools and setup Linux how I like it
apt-get install -y \
  exa grc ripgrep shellcheck zsh-autosuggestions \
  locate colordiff

# Setup the database for locate
nohup updatedb &

# Send notification that dotfiles post-start has completed
curl --silent \
  --form-string "token=$PUSHOVER_API_TOKEN" \
  --form-string "user=$PUSHOVER_USER_KEY" \
  --form-string "message=dotfiles script/codespaces-post-start complete for $CODESPACE_NAME!" \
  https://api.pushover.net/1/messages.json
