#!/usr/bin/env bash

log() { echo -e "\033[0;35m${1}\033[0m"; }

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

###############################################################################
# General UI/UX                                                               #
###############################################################################

log 'Disabling LSQuarantine dialog'
defaults write com.apple.LaunchServices LSQuarantine -bool false

log 'Disabling resume system-wide'
defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

log 'Restart on system freeze'
sudo systemsetup -setrestartfreeze on

log 'Disabling automatic capitalization'
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

log 'Diabling automatic dash substitution'
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

log 'Disabling automatic period substitution'
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

log 'Disabling automatic quote substitution'
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

log 'Disabling autocorrect'
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################

log 'Enabling Tap-To-Click'
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

log 'Enabling trackpad corner secondary click'
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true

###############################################################################
# Screen                                                                      #
###############################################################################

log 'Require password immediately on screensaver'
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

###############################################################################
# Finder                                                                      #
###############################################################################

log 'Setting ${HOME} as default location for Finder windows'
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"

log 'Show icons for hard drives, servers, and removable media on the Desktop'
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

log 'Show all filename extensions'
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

log 'Disabling the warning when changing a file extension'
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

log 'Disabling creation of .DS_Store files on network or USB volumes'
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

log 'Enabling snap-to-grid for icons on the desktop and in other icon views'
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

log 'Setting column view in all Finder windows by default'
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

log 'Disabling the warning before emptying the Trash'
defaults write com.apple.finder WarnOnEmptyTrash -bool false

log 'Showing the ~/Library folder'
chflags nohidden ~/Library

log 'Showing the /Volumes folder'
sudo chflags nohidden /Volumes

###############################################################################
# Safari & WebKit                                                             #
###############################################################################

log 'Disable Quick Website Search'
defaults write com.apple.Safari WebsiteSpecificSearchEnabled -bool false

log 'Press Tab to highlight each item on a web page'
defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks -bool true

log 'Show the full URL in the address bar (note: this still hides the scheme)'
defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true

log 'Set Safari’s home page to about:blank for faster loading'
defaults write com.apple.Safari HomePage -string "about:blank"

log 'Prevent Safari from opening ‘safe’ files automatically after downloading'
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

log 'Allow hitting the Backspace key to go to the previous page in history'
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool true

log 'Hide Safari’s bookmarks bar by default'
defaults write com.apple.Safari ShowFavoritesBar -bool false

log 'Make Safari’s search banners default to Contains instead of Starts With'
defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

log 'Remove useless icons from Safari’s bookmarks bar'
defaults write com.apple.Safari ProxiesInBookmarksBar "()"

log 'Enable the Develop menu and the Web Inspector in Safari'
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

log 'Add a context menu item for showing the Web Inspector in web views'
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

log 'Enable continuous spellchecking'
defaults write com.apple.Safari WebContinuousSpellCheckingEnabled -bool true

log 'Disable auto-correct'
defaults write com.apple.Safari WebAutomaticSpellingCorrectionEnabled -bool false

log 'Disable AutoFill'
defaults write com.apple.Safari AutoFillFromAddressBook -bool false
defaults write com.apple.Safari AutoFillPasswords -bool false
defaults write com.apple.Safari AutoFillCreditCardData -bool false
defaults write com.apple.Safari AutoFillMiscellaneousForms -bool false

log 'Warn about fraudulent websites'
defaults write com.apple.Safari WarnAboutFraudulentWebsites -bool true

log 'Disable plug-ins'
defaults write com.apple.Safari WebKitPluginsEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2PluginsEnabled -bool false

log 'Disable Java'
defaults write com.apple.Safari WebKitJavaEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled -bool false

log 'Block pop-up windows'
defaults write com.apple.Safari WebKitJavaScriptCanOpenWindowsAutomatically -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptCanOpenWindowsAutomatically -bool false

log 'Enable Do Not Track'
defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true

log 'Update extensions automatically'
defaults write com.apple.Safari InstallExtensionUpdatesAutomatically -bool true

###############################################################################
# TextEdit                                                                    #
###############################################################################

log 'Use plain text mode for new TextEdit documents'
defaults write com.apple.TextEdit RichText -int 0

log 'Open and save files as UTF-8 in TextEdit'
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

###############################################################################
# Mac App Store                                                               #
###############################################################################

log 'Enable the automatic update check'
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

log 'Check for software updates daily, not just once per week'
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

log 'Download newly available updates in background'
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

log 'Install System data files & security updates'
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

log 'Turn on app auto-update'
defaults write com.apple.commerce AutoUpdate -bool true

log 'Allow the App Store to reboot machine on macOS updates'
defaults write com.apple.commerce AutoUpdateRestartRequired -bool true

###############################################################################
# Photos                                                                      #
###############################################################################

log 'Prevent Photos from opening automatically when devices are plugged in'
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

###############################################################################
# Messages                                                                    #
###############################################################################

log 'Disable smart quotes as it’s annoying for messages that contain code'
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false

log 'Disable continuous spell checking'
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "continuousSpellCheckingEnabled" -bool false

###############################################################################
# Security                                                                    #
###############################################################################

log 'Enable Firewall globally'
sudo defaults write /Library/Preferences/com.apple.alf globalstate 1

log 'Enable Firewall stealth mode'
sudo defaults write /Library/Preferences/com.apple.alf stealthenabled 1

log 'Disable IR remote control'
sudo defaults write /Library/Preferences/com.apple.driver.AppleIRController DeviceEnabled -bool false

log 'Disable wifi captive portal'
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.captive.control Active -bool false

log 'Do not show password hints'
sudo defaults write /Library/Preferences/com.apple.loginwindow RetriesUntilHint -int 0

log 'Destroy FileVault key when going into standby mode, forcing a re-auth'
sudo pmset destroyfvkeyonstandby 1

log 'Enable secure virtual memory'
sudo defaults write /Library/Preferences/com.apple.virtualMemory UseEncryptedSwap -bool true

log 'Disable Bonjour multicast advertisements'
sudo defaults write /Library/Preferences/com.apple.mDNSResponder.plist NoMulticastAdvertisements -bool true

log 'Disable the crash reporter'
defaults write com.apple.CrashReporter DialogType -string "none"

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in "cfprefsd" \
	"Dock" \
	"Finder" \
	"Messages" \
	"Photos" \
	"Safari" \
	"SystemUIServer" \
	"TextEdit"; do
	killall "${app}" &> /dev/null
done
log 'Done. Note that some of these changes require a logout/restart to take effect'
