#!/usr/bin/env bash -e

log() { echo -e "\033[0;35m${1}...\033[0m"; }

if ! command -v dockutil >/dev/null
then
  log 'Installing Dockutil'
  brew install dockutil
fi

log 'Removing all Dock items'
dockutil --remove all

log 'Adding back Dock items'
dockutil --add /Applications/Launchpad.app
dockutil --add /Applications/Google\ Chrome.app
dockutil --add /Applications/Messages.app
dockutil --add /Applications/iTunes.app
dockutil --add /Applications/App\ Store.app
dockutil --add /Applications/Mail.app
dockutil --add /Applications/Utilities/Terminal.app
dockutil --add /Applications/System\ Preferences.app
dockutil --add /Applications/Visual\ Studio\ Code.app
dockutil --add /Applications/Sequel\ Pro.app
dockutil --add /Applications/Steam.app
dockutil --add "$HOME/Downloads" --display stack
