#!/bin/bash
set -e

if ! [ -L ~/.gnupg ] || ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

if ! command -v op >/dev/null
then
  brew cask install onepassword-cli
fi

onepassword_login() {
  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_mcquaid" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin mcquaid.1password.com mike@mikemcquaid.com)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get xrenp5t62jem7nz6arxaswsica .ssh/id_ed25519
onepassword_get zagw7lmcsbhszhkfpxeacdyhza .ssh/id_rsa
onepassword_get 3sjbzdhzfzcr3o52qrojwjgjjq .gnupg/mike@mikemcquaid.com.private.gpg-key

echo "Setting up GPG..."
chmod 700 ~/.gnupg
gpg --import ~/.gnupg/mike@mikemcquaid.com.public.gpg-key \
             ~/.gnupg/mike@mikemcquaid.com.private.gpg-key
