#!/bin/bash
set -e

if ! [ -L ~/.gnupg ] || ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    brew cask install onepassword-cli
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_mcquaid" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin mcquaid.1password.com mike@mikemcquaid.com)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get xrenp5t62jem7nz6arxaswsica .ssh/id_ed25519
onepassword_get zagw7lmcsbhszhkfpxeacdyhza .ssh/id_rsa
onepassword_get 3sjbzdhzfzcr3o52qrojwjgjjq .gnupg/mike@mikemcquaid.com.private.gpg-key

if ! [ -f "$HOME/.secrets" ]
then
  echo "Extracting secrets..."
  if ! command -v jq >/dev/null
  then
    brew install jq
  fi
  onepassword_login
  BINTRAY_KEY=$(op get item t6wkb3pguncltiehjfoeft3r6q | jq -r '.details.sections[1].fields[].v')
  cat > "$HOME/.secrets" <<EOF
export BINTRAY_KEY=$BINTRAY_KEY
EOF
  chmod 600 "$HOME/.secrets"
fi

echo "Storing SSH keys in keychain..."
ssh-add -K

echo "Setting up GPG..."
chmod 700 ~/.gnupg
gpg --import ~/.gnupg/mike@mikemcquaid.com.public.gpg-key \
             ~/.gnupg/mike@mikemcquaid.com.private.gpg-key
