#!/usr/bin/env bash -e

log() { echo -e "\033[0;35m${1}\033[0m"; }

if ! command -v code >/dev/null
then
  brew cask install visual-studio-code
fi

EXTENSIONS="$(code --list-extensions)"

for EXTENSION in $(cat $(dirname $0)/../vscode-extensions)
do
  if echo "$EXTENSIONS" | grep -q "$EXTENSION"
  then
    log "Extension '$EXTENSION' is already installed"
  else
    code --install-extension "$EXTENSION"
  fi
done
