#!/bin/bash
set -e

if ! command -v code >/dev/null
then
  if [ $(uname -s) = "Darwin" ]
  then
    brew cask install code
  else
    echo "Install VS Code first!" >&2
    exit 1
  fi
fi

EXTENSIONS="$(code --list-extensions)"

for EXTENSION in $(cat $(dirname $0)/../vscode-extensions)
do
  if echo "$EXTENSIONS" | grep -q "$EXTENSION"
  then
    echo "Extension '$EXTENSION' is already installed."
  else
    code --install-extension "$EXTENSION"
  fi
done
