#!/bin/bash
# Run by script/setup on Linux

set -eo pipefail

cd "$(dirname "$0")/.." || exit

# Add GitHub credentials if missing
if command -v "gh" >/dev/null && ! gh auth token &>/dev/null; then
  gh auth login --git-protocol https --hostname github.com --web
fi

# Use ZSH as my default Shell
if [[ "${SHELL}" != "/usr/bin/zsh" ]]; then
  sudo chsh -s /usr/bin/zsh "${USER}"
fi

# Install stuff from apt-get if needed
RERUN_SETUP=
if command -v "apt-get" &>/dev/null; then
  APT_GET_PACKAGES=()
  if ! command -v "gh" &>/dev/null; then
    APT_GET_PACKAGES+=(gh)
  fi
  if ! command -v "ruby" &>/dev/null; then
    APT_GET_PACKAGES+=(ruby)
    RERUN_SETUP=1
  fi
  if [[ -n "${WSL}" ]] && ! command -v "wslview" &>/dev/null; then
    APT_GET_PACKAGES+=(wslu)
  fi
  if [[ "${#APT_GET_PACKAGES[@]}" -gt 0 ]]; then
    echo "Updating apt-get..."
    sudo apt-get update
    sudo apt-get install -y "${APT_GET_PACKAGES[@]}"
  fi
fi

if [[ -n "${RERUN_SETUP}" ]]; then
  exec script/setup --skip-after-setup
fi
