#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd $(dirname $0)/..

# Create dev directory
mkdir dev

# Use ZSH as my default Shell
if [ "$SHELL" != "/bin/zsh" ]; then
  chsh -s /bin/zsh mike
fi

bin/touchid-enable-pam-sudo

# Ensure auto-update is always enabled
sudo defaults write /Library/Preferences/com.apple.commerce.plist AutoUpdate 1
